org: nikita1917
app: trellonikita
service: trellonikita

frameworkVersion: '2 || 3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  params:
    handler: handler.hello
    events:
      - httpApi:
          method: GET
          path: /hello
