# org: nikita1917
app: trellonikita
service: trellonikita

frameworkVersion: '2 || 3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  lambdaHashingVersion: 20201221
  httpApi:
    cors: true
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

custom:
  tableName: nikita-trello-dashboards

functions:
  dashboardGet:
    handler: crudDashboard/dashboardGet.handler
    events:
      - httpApi:
          method: GET
          path: /dashboardGet
  dashboardPut:
    handler: crudDashboard/dashboardPut.handler
    events:
      - httpApi:
          method: POST
          path: /dashboardPut
  dashboardUpdate:
    handler: crudDashboard/dashboardUpdate.handler
    events:
      - httpApi:
          method: PUT
          path: /dashboardUpdate
  dashboardDelete:
    handler: crudDashboard/dashboardDelete.handler
    events:
      - httpApi:
          method: DELETE
          path: /dashboardDelete